_BASE_: "230103_randresize_full.yaml"

SOLVER:
  MAX_ITER: 1200           # much smaller than full 3000
  STEPS: [400, 800]        # small LR decay schedule
  CHECKPOINT_PERIOD: 400
  BASE_LR: 1e-4            # slower LR for fine-tuning
  IMS_PER_BATCH: 2
  WARMUP_ITERS: 100

INPUT:
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 1024
  RANDOM_FLIP: "horizontal"

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True

MODEL:
  WEIGHTS: "weights/230103_randresize_full.pth"   # Detectree2 pretrained backbone
  MASK_ON: True