# config/fast_train.yaml
_BASE_: "base.yaml"

SOLVER:
  MAX_ITER: 1200
  STEPS: [400, 800]
  CHECKPOINT_PERIOD: 400
  BASE_LR: 1e-4
  IMS_PER_BATCH: 2
  WARMUP_ITERS: 100

INPUT:
  MIN_SIZE_TRAIN: 512
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 1024
  RANDOM_FLIP: "horizontal"

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True