# config/tiny_train.yaml
_BASE_: "base.yaml"

SOLVER:
  MAX_ITER: 50
  STEPS: []
  CHECKPOINT_PERIOD: 50
  BASE_LR: 1e-4
  IMS_PER_BATCH: 1
  WARMUP_ITERS: 0

INPUT:
  MIN_SIZE_TRAIN: 256
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 256
  MAX_SIZE_TEST: 512
  RANDOM_FLIP: "horizontal"

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True